#tomcat config
server:
  port: 8083


spring:

  datasource:
    druid:
      #jdbc config 数据库连接信息
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/testgfg?serverTimezone=CTT&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      filters: stat
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      #WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
      #StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        #监控页面
        url-pattern: /druid/*
        #不开启重置功能
        reset-enable: true
        # 登录账号
        login-username: admin
        # 登录密码
        login-password: 123
        #设置白名单
        allow: 127.0.0.1
        #设置黑名单
        #deny:

  #jpa config
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  #thymeleaf配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html
